### ISSUE TITLE
RestClient && VCR && Webmock always raising timeout

### ISSUE THREAD

**Issue by 42thcoder** [eliotsykes/rspec-rails-examples#119]
I got codes roughly like this:

```ruby
require 'vcr'
require 'webmock/rspec'

VCR.configure do |config|
  config.hook_into :webmock
  config.configure_rspec_metadata!
end

describe Test do
  it 'always timeout', :vcr do
    response = RestClient.post(url, req_body, req_headers)
  end
end
```

And I always got `Timeout` error: 

```
[Cassette: 'Car/#save_change_car_no/works'] Initialized with options: {:record=>:once, :match_requests_on=>[:method, :ignore_query_param_ordering], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system}
[webmock] Handling request: [post http://rs.qiniu.com/delete/c2tpby1ib3NzOua1mUEwMDAwMQ==] (disabled: false)
  [Cassette: 'Car/#save_change_car_no/works'] Initialized HTTPInteractionList with request matchers [:method, :ignore_query_param_ordering] and 0 interaction(s): {  }
[webmock] Identified request type (recordable) for [post http://rs.qiniu.com/delete/c2tpby1ib3NzOua1mUEwMDAwMQ==]

RestClient::RequestTimeout: Request Timeout
./spec/models/test_spec.rb:219:in `block (3 levels) in <top (required)>'
./spec/rails_helper.rb:50:in `block (3 levels) in <top (required)>'
./spec/rails_helper.rb:50:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
------------------
--- Caused by: ---
Net::OpenTimeout:
  execution expired
```

PS: The code run perfectly in `rails console`, so the network is fine.

By the way, thanks your work~ . @eliotsykes

**Comment by eliotsykes** [comment]
Hi @42thcoder - thanks for the thanks and I'll try to help briefly (you would be better off posting on StackOverflow). 

Based on the `RequestTimeout` error, the next thing to consider trying is increasing the timeout. Here's some guidance: https://stackoverflow.com/questions/10483418/how-to-set-timeout-in-restclient-gem-in-ruby
